### ISSUE TITLE
盤面がみづらい

### ISSUE THREAD

**Issue by ghost** [shionhonda/IaGo#1]
以前の版では盤面はマスの高さと横幅が同じで観やすかったのですが、さきほどcloneしたところ、横幅のほうが大きくなってしまっていて、対角線のコマの利きが見づらいです。

よろしくお願いします。
![image](https://user-images.githubusercontent.com/2049977/40537210-5510a12e-6049-11e8-81e9-1bf7dfd3e1c8.png)

**Comment by shionhonda** [comment]
ご指摘ありがとうございます！
stateをfloatで保存したことが原因でした。
さっそく訂正いたしました。
